### ISSUE TITLE
not compiling on vs2012

### ISSUE THREAD

**Issue by natxopedreira** [ofTheo/ofxAppGLFWWindowMulti#2]
Im trying to compile this using oF 0.8.3 vs2012 and get those errors

error C2664: 'glfwSetKeyCallback' : cannot convert parameter 2 from 'void (__cdecl *)(GLFWwindow *,int,int,int,int)' to 'GLFWkeyfun'

error C2664: 'glfwSetDropCallback' : cannot convert parameter 2 from 'void (__cdecl *)(GLFWwindow *,const char *)' to 'GLFWdropfun'

**Comment by ofTheo** [comment]
Hey yes this was setup for the 0.8.1 GLFW callbacks. 
I just made a branch for 0.8.2 / 0.8.3 here: https://github.com/ofTheo/ofxAppGLFWWindowMulti/tree/0.8.2

See if that works for you. 
also check this thread here for potential VAO issues on windows. 
http://forum.openframeworks.cc/t/multiple-screens-2014/

Cheers!
Theo

**Comment by natxopedreira** [comment]
Thanks theo, it works for me :)

Best
Natxo
